version: "3.8"

services:
  nmap-watcher:
    build: .
    container_name: nmap-watcher

    env_file:
      - .env

    volumes:
      - ./:/app:rw

    network_mode: "host"

    restart: unless-stopped

    tty: true